### ISSUE TITLE
Slow PUTs

### ISSUE THREAD

**Issue by aaronstephenson** [miki725/django-rest-framework-bulk#26]
Bulk PUT requests to my services are taking between 30 and 40 seconds to complete successfully. Bulk POST requests complete successfully in under 1 second. I've tried submitting various numbers of objects, between 1 and 20, using both methods and the response times don't seem to vary much.

Why do you think the PUTs are taking so long?

I'm using Python 3.4, Django 1.7, DRF 2.4.4, DRF-bulk 0.1.3, with PostgreSQL 9.3 and the default Django web development server on the backend.

**Comment by hackedd** [comment]
I ran into the same issue yesterday. I tracked it down to the way validation is handled in `BulkUpdateModelMixin`. In `bulk_update()` a [serializer is created](https://github.com/miki725/django-rest-framework-bulk/blob/615393d/rest_framework_bulk/drf2/mixins.py#L73-L78) with the QuerySet for the view, and then validated. The [validation](https://github.com/tomchristie/django-rest-framework/blob/2.4.8/rest_framework/serializers.py#L528-L529) in `BaseSerializer` loops over the entire QuerySet to extract their identities, which can be very slow, especially if you have a lot of records.

I worked around the issue by adding an [extra filter](https://gist.github.com/hackedd/d97ca2f282b53c33f990) to the affected views, that checks if it looks like a bulk update is in process, and filters the QuerySet to only those items that are about to be updated.
