### ISSUE TITLE
Atomic rollback does not occur when POST request fails part way through

### ISSUE THREAD

**Issue by alan-unravel** [miki725/django-rest-framework-bulk#32]
Could you shed any light on this? Thanks?

**Comment by miki725** [comment]
what is the issue? what DRF version? etc

**Comment by alan-unravel** [comment]
If I am posting a large dataset and the request is interrupted before finishing then partial data remains in my database and the transactions are not rolled back. The DRF version is 2.4.3. Thanks for the fast reply!

**Comment by miki725** [comment]
Not sure what is an easy answer for this. DRF-bulk uses DRF serializers to save bulk data since its introduction (e.g. `many=True`). You can try overriding some logic in serializers save logic to preserve atomic behavior.

**Comment by alan-unravel** [comment]
Okay, thanks for your help!
